- name: Provision CICS region data sets in intial state and start it
  hosts: all
  gather_facts: false
  environment: "{{ environment_vars }}"

  vars:
    applid: CICSTU01
    cmci_port: 2700

  module_defaults:
    group/ibm.ibm_zos_cics.region:
      state: initial
      cics_data_sets:
        template: "CICSTS.V6R1M0.CICS.<< lib_name >>"
      region_data_sets:
        template: "CICSTU.{{ applid }}.<< data_set_name >>"
      le_data_sets:
        template: "CEE.<< lib_name >>"
      cpsm_data_sets:
        template:  "CICSTS.V6R1M0.CPSM.<< lib_name >>"

  tasks:
    - name: Create the auxiliary temporary storage data set (DFHTEMP)
      ibm.ibm_zos_cics.aux_temp_storage:

    - name: Create the auxiliary trace data set (DFHAUXT)
      ibm.ibm_zos_cics.aux_trace:

    - name: Create the second auxiliary trace data set (DFHBUXT)
      ibm.ibm_zos_cics.aux_trace:
        destination: B

    - name: Create the transaction dump data set (DFHDMPA)
      ibm.ibm_zos_cics.transaction_dump:

    - name: Create the second transaction dump data set (DFHDMPB)
      ibm.ibm_zos_cics.transaction_dump:
        destination: B

    - name: Create the CSD data set (DFHCSD)
      ibm.ibm_zos_cics.csd:

    - name: Update the CSD data set with the CSDUP script
      ibm.ibm_zos_cics.csd:
        state: changed
        input_location: INLINE
        input_content: ADD GROUP(DFHTERMC) LIST(DFHLIST1)

    - name: Create the transient data intrapartition data set (DFHINTRA)
      ibm.ibm_zos_cics.td_intrapartition:

    - name: Create the local request queue data set (DFHLRQ)
      ibm.ibm_zos_cics.local_request_queue:

    - name: Create the global catalog data set (DFHGCD)
      ibm.ibm_zos_cics.global_catalog:

    - name: Create the local catalog data set (DFHLCD)
      ibm.ibm_zos_cics.local_catalog:

    - name: Create CICS JCL
      ibm.ibm_zos_cics.region_jcl:
        applid: "{{ applid }}"
        job_parameters:
          region: 0M
        sit_parameters:
          start: AUTO
          sit: 6$
          aicons: AUTO
          edsalim: 500M
          grplist: (DFHLIST*)
          gmtext: Region provisioned with Ansible using IBM watsonx Assistant for Z
          tcpip: "YES"
          usshome: /usr/lpp/cicsts/cicsts61/
          sysidnt: KYE1
          cpsmconn: "NO"
          sec: "NO"

    - name: Submit region JCL
      ansible.builtin.command:
        cmd: jsub "CICSTU.{{ applid }}.DFHSTART"
      changed_when: True