# (C) Copyright IBM Corp. 2024
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Provision CICS region data sets in intial state and start it
  hosts: all
  gather_facts: false
  vars_files: "{{ playbook_dir }}/host_vars/variables.yml"
  environment: "{{ environment_vars }}"

  vars:
    applid: CICSTU01
    cmci_port: 2700

  module_defaults:
    group/ibm.ibm_zos_cics.region:
      state: initial
      region_data_sets:
        dfhauxt:
          dsn: "CICSTU.{{ applid }}.DFHAUXT"
        dfhbuxt:
          dsn: "CICSTU.{{ applid }}.DFHBUXT"
        dfhdmpa:
          dsn: "CICSTU.{{ applid }}.DFHDMPA"
        dfhdmpb:
          dsn: "CICSTU.{{ applid }}.DFHDMPB"
        dfhcsd:
          dsn: "CICSTU.{{ applid }}.DFHCSD"
        dfhgcd:
          dsn: "CICSTU.{{ applid }}.DFHGCD"
        dfhlcd:
          dsn: "CICSTU.{{ applid }}.DFHLCD"
        dfhlrq:
          dsn: "CICSTU.{{ applid }}.DFHLRQ"
        dfhintra:
          dsn: "CICSTU.{{ applid }}.DFHINTRA"
        dfhtemp:
          dsn: "CICSTU.{{ applid }}.DFHTEMP"
        dfhstart:
          dsn: "CICSTU.{{ applid }}.DFHSTART"
      cics_data_sets:
        sdfhauth:  "CICSTS.V6R1M0.CICS.SDFHAUTH"
        sdfhlic: "CICSTS.V6R1M0.CICS.SDFHLIC"
        sdfhload: "CICSTS.V6R1M0.CICS.SDFHLOAD"
      cpsm_data_sets:
        seyuauth: "CICSTS.V6R1M0.CPSM.SEYUAUTH"
        seyuload: "CICSTS.V6R1M0.CPSM.SEYULOAD"
      le_data_sets:
        sceecics: "CEE.SCEECICS"
        sceerun: "CEE.SCEERUN"
        sceerun2: "CEE.SCEERUN2"

  tasks:
    - name: Create the auxiliary temporary storage data set (DFHTEMP)
      ibm.ibm_zos_cics.aux_temp_storage:

    - name: Create the auxiliary trace data set (DFHAUXT)
      ibm.ibm_zos_cics.aux_trace:

    - name: Create the second auxiliary trace data set (DFHBUXT)
      ibm.ibm_zos_cics.aux_trace:
        destination: B

    - name: Create the transaction dump data set (DFHDMPA)
      ibm.ibm_zos_cics.transaction_dump:

    - name: Create the second transaction dump data set (DFHDMPB)
      ibm.ibm_zos_cics.transaction_dump:
        destination: B

    - name: Create the CSD data set (DFHCSD)
      ibm.ibm_zos_cics.csd:

    - name: Update the CSD data set
      ibm.ibm_zos_cics.csd:
        state: changed
        input_location: INLINE
        input_content: |
            ADD GROUP(DFHTERMC) LIST(DFHLIST1)
            COPY GROUP(DFH$WU) TO(WUIGRP)
            ALTER TCPIPSERVICE(DFH$WUTC)   GROUP(WUIGRP)  PORT({{ cmci_port }})
            ADD GROUP(WUIGRP) LIST(DFHLIST1)

    - name: Create the transient data intrapartition data set (DFHINTRA)
      ibm.ibm_zos_cics.td_intrapartition:

    - name: Create the local request queue data set (DFHLRQ)
      ibm.ibm_zos_cics.local_request_queue:

    - name: Create the global catalog data set (DFHGCD)
      ibm.ibm_zos_cics.global_catalog:

    - name: Create the local catalog data set (DFHLCD)
      ibm.ibm_zos_cics.local_catalog:

    - name: Create CICS JCL
      ibm.ibm_zos_cics.region_jcl:
        applid: "{{ applid }}"
        dfhrpl:
          data_sets: "ALICIA.CICS.LOADLIB"
        job_parameters:
          region: 0M
        sit_parameters:
          start: AUTO
          sit: 6$
          aicons: AUTO
          edsalim: 500M
          grplist: (DFHLIST*)
          gmtext: Region provisioned with Ansible using IBM watsonx Assistant for Z
          tcpip: "YES"
          usshome: /usr/lpp/cicsts/cicsts61/
          sysidnt: KYE1
          sec: "NO"
          csdrecov: "NONE"

    - name: Submit region JCL
      ansible.builtin.command:
        cmd: jsub "CICSTU.{{ applid }}.DFHSTART"
      changed_when: True